version: "3.9"
services:
    # Node.jsアプリケーションのサービス
    app:
        # Dockerfileを使用してビルド
        build: .
        # ポート3000をホストのポート3000にマッピング
        ports:
            - "3000:3000"
        # ボリュームをマウント
        volumes:
            - .:/app
            - /app/node_modules

        # 開発モードで実行
        command: ["npm", "run", "dev"]
